name: Build and push base - on push

on:
  push:
  schedule:
    - cron: '0 1 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag labordigital/unison:2.48.2
      - name: Push the tagged Docker image
        run: docker push labordigital/unison:2.48.2

